title: 刘璇
description: 中山大学 Sun Yat-Sen University
site_title: '@Liu Xuan - Personal Homepage'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: scarlet0703
blog_url: #https://www.nagekar.com
email: liux687@mail2.sysu.edu.cn
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/profile2.png

# Google Analytics ID
google_analytics: 
